# conda env create|update --file environment.yml
name: colorpicker
dependencies:
- python=3.6
- pip
- pip:
  - '--editable=.'
  - flake8
  - flake8-quotes
  - numpy==1.16.*
  - pandas==0.24.1
  - pytest
  - pytest-mock
  - scipy
  - torch
  - connexion
  - flask-cors
